"""db creation

Revision ID: daa533ac368a
Revises: 
Create Date: 2023-07-31 11:21:59.807939

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'daa533ac368a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'uuid',
                    existing_type=sa.UUID(),
                    nullable=False)
    op.alter_column('entries', 'text',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'text',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('entries', 'uuid',
                    existing_type=sa.UUID(),
                    nullable=True)
    # ### end Alembic commands ###
